-- 코드를 작성해주세요
SELECT C.ID
FROM ECOLI_DATA A 
    LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
    LEFT JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID
WHERE A.PARENT_ID IS NULL AND C.ID IS NOT NULL
GROUP BY C.ID
ORDER BY C.ID ASC