-- 코드를 작성해주세요
-- 부모가 레어인 아이템 리스트
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I 
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
LEFT JOIN ITEM_INFO I2 ON T.PARENT_ITEM_ID = I2.ITEM_ID
WHERE I2.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC